apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm.fullname" . }}-master-key
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
type: Opaque
stringData:
  key: {{ .Values.masterKey | quote }}
