apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vllm-inference.fullname" . }}-model-cache
  labels:
    {{- include "vllm-inference.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- with .Values.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
