{{- if .Values.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm-inference.fullname" . }}-api-key
  labels:
    {{- include "vllm-inference.labels" . | nindent 4 }}
type: Opaque
stringData:
  key: {{ .Values.apiKey | quote }}
{{- end }}
