apiVersion: v1
kind: Service
metadata:
  name: {{ include "comfyui.fullname" . }}
  labels:
    {{- include "comfyui.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8188
      targetPort: http
      protocol: TCP
  selector:
    {{- include "comfyui.selectorLabels" . | nindent 4 }}
